### ISSUE TITLE
ModuleNotFoundError: No module named 'tpolicies'

### ISSUE THREAD

**Issue by SergioTermann** [tencent-ailab/TLeague#1]
Hi , I met an error when running 'bash example_pong2p_sp_ppo.sh learner'
 from 
https://github.com/tencent-ailab/TLeague/blob/dev-open/docs/EXAMPLE_PONG2P_SP_PPO.md.
""ModuleNotFoundError: No module named 'tpolicies' "
How can I install tpolicies?

**Comment by pengsun** [comment]
Hi, currently please see the descriptions here:
https://github.com/tencent-ailab/tleague_projpage#minimal-working-example
one needs manually install the packages `TLeague`, `TPolicies`, `Arena`, respectively.
We'll provide the Dockerfile to clarify the full installation soon.

**Comment by pengsun** [comment]
Hi, we've updated README and TPolicies/setup.py to clarify the installation, see the commits https://github.com/tencent-ailab/TPolicies/commit/b488e9dc128b89df98844a75e5e82396232752eb and https://github.com/tencent-ailab/tleague_projpage/commit/ffa79b392200283e9a11532df6871cda9bb9bd72

Also, here is an example of how to build the docker image (for TLeague + ViZDoom):
https://github.com/tencent-ailab/TLeagueVdAutoBuild

This should address the issue. Closing, feel free to reopen it if the problem remains.

**Comment by SergioTermann** [comment]
Thanks！

**Comment by laszukdawid** [comment]
Hi team,

If it isn't a big change, could you please add this information explicitly to this project's Readme? I just encoutered this problem while trying to run Pommerman example.
