### ISSUE TITLE
 make_sc2full_v8_interface got an unexpected keyword argument 'max_bo_count'

### ISSUE THREAD

**Issue by JamiePlur** [tencent-ailab/TLeague#11]
I installed the env as instructed in https://github.com/tencent-ailab/TImitate
but it got a unexpected keyword argument error when run learner:
`bash example_sc2_sp_ppo_infserver.sh learner`

is there any problem with the code?

(my runtime: python3.6.5.  tensorflow 1.15.0)

**Comment by norybaby** [comment]
I got this problem too  when i ran  bash example_sc2_sp_ppo2.sh learner

**Comment by slivermoda** [comment]
Please update to the latest commits. These errors raise from inconsistent versions of TLeague and TImitate.
