### ISSUE TITLE
Actor 是本地在运行模型的吗?

### ISSUE THREAD

**Issue by Passerby** [tencent-ailab/TLeague#12]
我看到 Actor 获取 task 向模型池拿模型下发到本地，那每个 Actor 不都要运行一个 tf sess，这样好像对资源消耗很大？好像没找到哪里有用到 inf server，是不是只有 train 进行训练那一端才使用 inf server?

**Comment by pengsun** [comment]
Yes, each Actor lives in a separate process, which is convenient for isolation and deployment with containers (and container compilation tool) in a large scale run that typically includes thousands of actors across many physical machines.

An `Actor` bears an `Agent`. It is the Agent who (optionally) uses the inference server. Code can be found here:
https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/actors/actor.py#L66
https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/actors/agent.py#L91-L117
