### ISSUE TITLE
Sampling from Experience Replay during Imitation Learning

### ISSUE THREAD

**Issue by MorganeAyle** [tencent-ailab/TLeague#13]
Hello,

During Imitation Learning, do you process the trajectories from the same replay in a sequential manner or do you randomly sample a trajectory from a random starting point in the replay? In the latter case, how do you keep track of the LSTM state so that the memory is maintained throughout the game?

Thank you!

**Comment by slivermoda** [comment]
We indeed used the former way that an entire episode was passed through the LSTM.
