### ISSUE TITLE
How about the efficiency of TLeague

### ISSUE THREAD

**Issue by cumttang** [tencent-ailab/TLeague#3]
Firstly, appreciate  your contribution to the community.

But  I'm wondering about the efficiency of these examples in a single machine. Since I have run this system on my personal server, it may take a long time but cannot see the agent (atari-game and pong-game) who becomes stronger than before. 

I have read the run shell and some parameters (batch size, unroll length and batch_num_worker) are very small. So I wonder that are there any better parameters that can be provided for a more impressive result with a shorter time for training.

Best regards!

**Comment by pengsun** [comment]
Hi, the Atari and Pong-2p code are just examples to show that TLeague can train with Single Agent RL, where the hyperparameters are arbitrary. We've not tuned them to make sure it leads to good performance. We should have clarified this in the doc.

**Comment by cumttang** [comment]
Thanks for your quick response! How about the pommer man or other games? Are they in the same situations (hyperparameters) as Atari and Pong-2p?

**Comment by pengsun** [comment]
Hi, for the single machine examples of Pommerman and other games, yes, the hyperparameters are arbitrary and no guarantee on performance, just examples to show it runs.

But we do plan to release the full training code of Pommeran for reproducing the results as discussed in the TLeague technical report. We'll provide the `.yml.jinja2` file where one can read off the interested hyperparameters or simply run it in a k8s cluster.

**Comment by cumttang** [comment]
That's great!
