### ISSUE TITLE
Which matching strategy do you use the most?

### ISSUE THREAD

**Issue by Passerby** [tencent-ailab/TLeague#6]
Which mgr do you use the most?
How to make a reasonable choice among them?

**Comment by pengsun** [comment]
I think the "uniform sampling"
https://github.com/tencent-ailab/tleague_projpage/blob/c8df899d713a77dcc72aa6e2b9d892bcebc96cf8/vizdoom/vdtr-frag-open.yml.jinja2#L60

and the "mixed sp-pfsp"
https://github.com/tencent-ailab/tleague_projpage/blob/c8df899d713a77dcc72aa6e2b9d892bcebc96cf8/pommerman/pommerman.yml.jinja2#L69

would be a good starting point.
