### ISSUE TITLE
what is pgn_file ?

### ISSUE THREAD

**Issue by Passerby** [tencent-ailab/TLeague#7]
https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/league_mgrs/league_mgr.py#L50

What is stored in the file?

**Comment by pengsun** [comment]
Hi, "pgn" stands for Portable Game Notation:
https://en.wikipedia.org/wiki/Portable_Game_Notation

And here you can find the code that writes pgn contents:
https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/game_mgr/base_game_mgr.py#L197

BTW, there exists powerful tool that recognizes the pgn file format, e.g., the Elo analysis code:
https://www.remi-coulom.fr/Bayesian-Elo/

**Comment by Passerby** [comment]
thanks
