### ISSUE TITLE
why learner add api for response learner id ?

### ISSUE THREAD

**Issue by Passerby** [tencent-ailab/TLeague#8]
https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/base_learner.py#L68

What does this API do?

Is it to serve some discovery/register services in cluster cloud?

**Comment by pengsun** [comment]
Hi, it serves for registering/discovering the `learner task` as defined here:
https://github.com/tencent-ailab/TLeague/blob/101ff8532bcc3ca547ed6b3b8808845596742b99/tleague/utils/tl_types.py#L19
where all the learner tasks are maintained at League Manager.

To be detailed, when using Horovod for multi-GPU training, TLeague has `M_L` learners which always synchronize the NN parameters, with each learner associated to only one GPU card.  Being consistent to the Horovod/mpi convention, we let `rank 0` learner sponsor the task creating (by calling the `_request_task`):
https://github.com/tencent-ailab/TLeague/blob/101ff8532bcc3ca547ed6b3b8808845596742b99/tleague/learners/pg_learner.py#L197

while other `rank i, i = 1, 2,...,M_L-1` learners query the existed learner task:
https://github.com/tencent-ailab/TLeague/blob/101ff8532bcc3ca547ed6b3b8808845596742b99/tleague/learners/pg_learner.py#L215

Note all the `M_L` learners have an identical `learner_id` (which is the handle for the learner task) as passed in by the `--learner_id` arg:
https://github.com/tencent-ailab/TLeague/blob/101ff8532bcc3ca547ed6b3b8808845596742b99/tleague/bin/run_pg_learner.py#L36
and the example here:
https://github.com/tencent-ailab/tleague_projpage/blob/c8df899d713a77dcc72aa6e2b9d892bcebc96cf8/pommerman/pommerman.yml.jinja2#L385

**Comment by Passerby** [comment]
thanks
