### ISSUE TITLE
Why don't you remove instance when you skip frame(step).

### ISSUE THREAD

**Issue by Passerby** [tencent-ailab/TLeague#9]
https://github.com/tencent-ailab/TLeague/blob/101ff8532bcc3ca547ed6b3b8808845596742b99/tleague/actors/ppo_actor.py#L98

skip的数据这里 `self._gamma ** (mb_skips[t]+1)`  gamma乘以了两次，这里让我很迷惑，为什么不直接去掉这个数据呢？🤔，是为了减小 next_value 中间略过一个step的影响吗? 有对比过和直接去掉之间效果上有什么差别吗

我的理解，skip 的时机类似英雄被晕眩的时候，actor 无法控制，这个时候是没有任何操作的，只能取一个空的 action，拿这样的数据去训练感觉没有很大的意义。

**Comment by slivermoda** [comment]
You can abandon these useless samples, however you should not ignore the actual delay of the discounted reward propagation.
